### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by MoritzWeber0** [traines-source/time-space-train-planner#1]
Hi, 

thanks for your tool. It looks amazing and should be exactly what I need. 

I just wanted to try it out, but can't get it to run. I built the Docker Image and started the Container with Port Forwarding of the Port 3000.  Unfortunately nothing is served on the `/` endpoint. 

So my questions are: 
- Do I have to set configuration variables? (I saw the `deployments/conf.example.env`. Can you explain the different entries in there?)
- On which endpoint is the frontend application served? 

Thanks already in advance! 
~ Moritz

**Comment by traines-source** [comment]
Hi,

I've extended the readme a bit to answer your questions.
Tip: Instead of setting up an HTTP cache, you can also directly use https://v5.db.transport.rest/, both for the backend (conf.env, hostname only) and the frontend (conf.js). But you shouldn't do that ;)

Let me know if that helps you!

**Comment by MoritzWeber0** [comment]
Thank you so much! It works for me perfectly on my local machine.
