### ISSUE TITLE
Displayed time span too short

### ISSUE THREAD

**Issue by leonheess** [traines-source/time-space-train-planner#17]
Example: https://tespace.traines.eu/tstp?from=8011160&to=8000096&vias=8010101&vias=8000244&vias=0&vias=0&vias=0&vias=0&vias=0&vias=0&vias=0&vias=0&datetime=2022-11-07T23%3A48

![Screenshot_20221107-235158](https://user-images.githubusercontent.com/13834296/200432590-7d3fa5b2-6e03-4679-a5da-d543519fffbe.jpg)

It shows many lines but no connection that ever arrives at the destination station. Btw: The Vias where added by the app. I just searched for Berlin - Stuttgart.

**Comment by traines-source** [comment]
Yeah, in this case, the retrieved/displayed time span is too short. So far, it is derived from the journey duration predicted by HAFAS, not taking into account the waiting time until departure (which is very long in this case). I've changed that now and updated the time span calculation in general (again). Should be live in a couple of minutes.
Thanks for reporting!
