### ISSUE TITLE
FeatureRequest nginx in docker-compose

### ISSUE THREAD

**Issue by FinnHuelsbusch** [traines-source/time-space-train-planner#2]
Hello nice project. 

I have a suggestion is it possible to add another  docker compose file with a nginx container as cache so that the setup is easier?
Or just add the nginx to the default compose file.  

Kind regards, 
Finn

**Comment by traines-source** [comment]
Hi,

I think that depends a bit on how and where you run it. But I have now provided a ready-to-use setup. When using it, you have to access TSTP via the reverse proxy, which is mapped to port 8080 in the docker-compose.
Anyways, I hope that I can soon provide a publicly hosted version of TSTP.

Let me know if that helps!

**Comment by FinnHuelsbusch** [comment]
Thank you, 
it works just fine. Hope that it enables others to easily use tstp.
